---
- name: Ensure app config directory exists
  file:
    path: "{{ app_config_path | dirname }}"
    state: directory

- name: Deploy application.yml from template
  template:
    src: application.yml.j2
    dest: "{{ app_config_path }}"
    mode: '0644'

- name: Launch backend application container
  docker_container:
    name: my_app
    image: "{{ app_image }}"
    networks:
      - my_app_network
    volumes:
      - "{{ app_config_path }}:/app/config/application.yml:ro"
    ports:
      - "8000:8000"
    state: started

