---
- name: Ensure app directory exists
  file:
    path: "{{ db_env_path | dirname }}"
    state: directory

- name: Deploy database .env from template
  template:
    src: .env.j2
    dest: "{{ db_env_path }}"
    mode: '0644'

- name: Launch PostgreSQL container
  docker_container:
    name: my_database
    image: postgres:15
    env_file: "{{ db_env_path }}"
    networks:
      - my_app_network
    state: started
