---
# tasks file for roles/proxy


- name: Run HTTPD reverse proxy
  docker_container:
    name: reverse_proxy
    image: francoisgonon/tp-devops-httpd
    pull: yes
    networks:
      - name: my_app_network
    ports:
      - "80:80"
    state: started

