name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Deploy Backend via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: admin
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Pull the latest backend image
            docker pull francois/devops-backend:latest
            
            # Restart only the backend container
            docker container restart backend-api || (
              echo "Container not running, starting new container..."
              docker run -d --name backend-api \
                --network app-network \
                -p 8080:8080 \
                francois/devops-backend:latest
            )
            
            echo "Backend service redeployed successfully"