name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: admin
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "ansible/"
          target: "/tmp/tp-devops-deployment"
      
      - name: Deploy via SSH command
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: admin
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |            # Check for required software
            command -v ansible-playbook >/dev/null 2>&1 || { echo "Installing Ansible..."; sudo apt-get update && sudo apt-get install -y ansible; }
            
            # Create an ansible config file to disable host key checking
            echo "[defaults]" > /tmp/ansible.cfg
            echo "host_key_checking = False" >> /tmp/ansible.cfg
            
            # Run ansible playbook directly from the copied files
            cd /tmp/tp-devops-deployment/ansible
            ANSIBLE_CONFIG=/tmp/ansible.cfg ansible-playbook -i inventories/setup.yml deploy-backend.yml