name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH command
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: admin
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/tp-devops-repo || git clone https://github.com/FrancoisGonon/tp-devops-correction-docker.git ~/tp-devops-repo
            cd ~/tp-devops-repo
            git pull
            cd ansible
            ansible-playbook -i inventories/setup.yml deploy-backend.yml